DROP TABLE schema2.t1; DROP TABLE schema1.t1; DROP TABLE t1; DROP SCHEMA schema2 CASCADE; DROP SCHEMA schema1 CASCADE;
DROP EXTERNAL TABLE ext_expenses;
DROP FOREIGN TABLE ft1; DROP USER MAPPING FOR testrole SERVER sc; DROP SERVER sc; DROP FOREIGN DATA WRAPPER fdw;
DROP TABLESPACE mytblspace;
DROP FUNCTION add(integer, integer);
DROP PROCEDURE insert_data;
DROP PROTOCOL p1; DROP FUNCTION f1;
DROP EXTENSION hstore;
DROP COLLATION collation_french;
DROP TYPE type_mood;
DROP PROCEDURAL LANGUAGE plperlabc; DROP FUNCTION plperl_call_handler;
DROP TRANSFORM FOR pg_catalog.int4 LANGUAGE c;
DROP TEXT SEARCH TEMPLATE public.testtemplate; DROP TEXT SEARCH PARSER public.testparser; DROP TEXT SEARCH DICTIONARY public.testdictionary; DROP TEXT SEARCH CONFIGURATION public.testconfiguration;
DROP OPERATOR FAMILY public.testclass USING gist; -- (before 5) DROP OPERATOR CLASS public.testclass USING gist;
DROP OPERATOR FAMILY public.testfam USING hash;
DROP AGGREGATE agg_twocols(numeric, numeric); DROP FUNCTION mycombine_accum; DROP FUNCTION mysfunc_accum;
DROP CAST (text AS int);
DROP ACCESS METHOD test_access_method;
DROP VIEW v_vista;
DROP MATERIALIZED VIEW v_comedies; DROP TABLE tbl_films;
DROP SEQUENCE myseq;
DROP TABLE tbl_with_constraint;
DROP DOMAIN us_postal_code_domain;
DROP CONVERSION public.testconv;
DROP TABLE books;
DROP RULE rule_abc ON t1_for_rule; DROP TABLE t1_for_rule; DROP TABLE t2_for_rule;
DROP EVENT TRIGGER postdata_eventtrigger; DROP FUNCTION public.postdata_eventtrigger_func; DROP TRIGGER testtable_trigger ON public.testtable; DROP TABLE testtable;
DROP ROLE jonathan;
DROP GROUP group1;
DROP USER user1;
DROP POLICY account_policy ON accounts; DROP TABLE accounts;
DROP RESOURCE GROUP rgroup1;
DROP RESOURCE QUEUE myqueue;
DROP STATISTICS s1; DROP TABLE s_t1;
